var  Levels=
[
[
  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
  "B*   0B B     B   B B B B         B B B     B     B     B   B     B   B",
  "B BBB B B BBBBBBB B B B B B BBBBB B B B BBB BBB BBBBB BBB BBB B BBBBB B",
  "B   BK          B B B     B B       B   B   B     B           B   B   B",
  "BBBBB BBBBBBB B B B B BBBBB BBBBB B B B BBBBBBB B B B B BBBBBBBBB B B B",
  "B B     B B B B B B B B B B   B B B   B       B B   B B B B   B     B B",
  "B B BBBBB B B BBB B B B B BBB B BBB BBB BBB BBBBBBBBB B B B BBB BBBBBBB",
  "B       B     B     B   B     B     B B   B B B       B B B   B   B   B",
  "BBB BBBBB BBBBB BBBBB BBB BBBBBBBBBBB B BBBBB B B BBBBB B B B BBBBB BBB",
  "B   B   B     B B B   B B B     B     B B       B   B B B   B       B B",
  "B B B B BBB BBB B B B B B BBB BBB B B B B B B BBBBBBB BBBBB BBBBBBB B B",
  "B B   B   B     B B B B B     B   B B     B B         B         B     B",
  "BBBBBBBBBBB B BBB B B B B BBBBBBBBBBB BBB BBBBB B BBBBBBBBBBB BBB BBB B",
  "B   B       B     B B B   B   B B B B B       B B           B   B B B B",
  "B BBBBBBBBBBBBB BBBBBBBBB BBB B B B B B BBBBBBBBBBBBBBBBBBB B B BBB B B",
  "B       B B   B                 B     B B B               B   B   B B B",
  "B B B B B B B BBB B BBBBB B B BBB B B B B BBBBB BBB BBBBB BBBBBBBBB B B",
  "B B B B B   B B B B B   B B B B   B B B   B       B B B B         B B B",
  "B BBBBBBB B BBB BBB B BBBBBBBBB B B BBBBB BBB BBB BBB B BBBBBBB BBB BBB",
  "B         B   B       B     B B B B     B B   B     B B   B B B     B B",
  "B B BBBBBBB B B B BBB B BBBBB B B B BBB BBBBB B B B B BBB B B BBB B B B",
  "B B       B B   B B           B B B   B       B B B         B     B  0B",
  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
],
[
  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
  "B*          B   B B               B B         B B B B B B         B   B",
  "BBB B BBBBB B BBB B B BBBBBBBBBBBBB B B B BBBBB B B B B B B B BBB BBB B",
  "B B B B   B0  B B   B B   B   B       B B   B B   B   B   B B B       B",
  "B B BBB BBBBBBB BBB BBBBB B BBBBBBBBBBB BBB B B BBB B B BBBBB BBB BBB B",
  "B     B           B     B   B B       B   B B       B   B     B B B   B",
  "B B BBB B B B B BBB BBB B BBB BBBBBBB B BBBBBBBBB BBBBB B BBBBB B BBB B",
  "B B     B B B B   B   B B   B   B   B           B B B   B     B   B   B",
  "B B BBBBBBB BBB BBB BBB B B B BBBBB BBB B BBB BBB B B BBBBBBBBB BBB B B",
  "B B B B       B   B   B B B B B B   B B B   B   B   B B B   B     B B B",
  "BBB B BBB BBBBBBBBBBB BBB B B B BBB B BBBBBBB BBBBBBB B B B BBBBB BBB B",
  "B     B B B   B           B B     B     B       B B     B B   B     B B",
  "BBBBB B BBBBB BBBBBBB B B BBB B B BBBBB BBB BBBBB BBB BBBBB BBB BBBBB B",
  "B           B B B     B B     B B       B   B       B B       B     B B",
  "B BBBBB B BBB B B BBB BBBBBBB BBB BBBBB B BBB BBBBBBB B B BBBBB BBB BBB",
  "B B   B B     B     B   B B     B   B           B     B B B     B   B B",
  "B BBB BBB BBB B BBB BBBBB BBBBB BBBBBBBBB B B BBBBB BBB BBBBBBBBB B B B",
  "B B B     B B B   B   B     B     B B   B B B       B             B B B",
  "B B BBBBB B B B BBB BBB B B B BBBBB BBB BBB BBBBBBB B B BBBBB B BBB B B",
  "B   B     B B   B       B B B B B   B B   B     B   B B B B   B   B   B",
  "B B BBB B B B B B BBB BBBBBBB B B B B B B BBBBBBB BBB B B BBBBBBBBBBB B",
  "B B   B B   B B B B     B         B     B   B       B B       B      0B",
  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
],
[
  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
  "B*    B B         B             B B   B     B   B   B   B     B B     B",
  "B B B B B BBBBB B BBBBBBB BBBBB B BBB B BBBBB BBB BBB BBBBBBB B BBB B B",
  "B B B B0    B   B B B     B   B       B B   B B B B B   B B B     B B B",
  "B BBB BBB BBB BBB B BBBBB B BBB B BBBBB B B B B B B BBB B B B BBB BBB B",
  "B B   B     B   B B     B B   B B B       B   B     B     B B B       B",
  "B B BBBBB B B BBBBB B B B B B BBBBBBBBB BBB BBBBB BBBBB B B B BBBBB BBB",
  "B B   B   B B     B B B   B B     B     B     B B   B B B B B   B   B B",
  "B BBBBB BBBBB BBB BBB BBBBBBBBB B B BBBBBBBBB B B B B B B B BBB BBB B B",
  "B   B     B     B B B           B B     B   B B   B     B B   B   B   B",
  "B B B BBBBB BBBBB B B BBBBB BBBBB BBBBB BBB B BBBBBBBBB BBB BBBBBBBBB B",
  "B B     B   B B   B     B B   B         B       B     B               B",
  "B BBBBBBBBB B B B B B B B BBB B BBBBBBB BBB BBBBBBBBB BBBBBBBBB B BBB B",
  "B         B   B B B B B B   B B     B     B B   B B   B       B B B   B",
  "B B BBBBB BBBBB BBBBB B B BBBBBBB B B BBBBB B BBB BBB BBBBB BBBBBBBBB B",
  "B B   B       B B   B B B   B     B B   B         B   B       B       B",
  "BBB B B BBBBB BBBBB B BBBBB B BBB BBBBBBBBBBB B BBBBB BBBBB BBBBB B B B",
  "B   B B   B B         B       B   B         B B B     B B B   B   B B B",
  "B BBB B BBB BBB BBB BBB BBB BBB BBBBBBB BBB BBB BBB BBB B B B B BBB B B",
  "B B   B B     B B B   B B   B   B   B B   B   B B     B B B B     B B B",
  "B BBBBBBB B BBBBB B B B B B BBB B B B B B BBB BBB BBB B B B BBB BBBBB B",
  "B       B B         B B B B   B   B     B   B       B       B       B0B",
  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
]
];
